// AUTO-GENERATED by `npm run rules:gen` — do not edit by hand.
import schengen from './schengen.json';
import uk from './uk.json';
import us from './us.json';

export const jurisdictionFiles: readonly unknown[] = [schengen, uk, us];
