/**
 * Regenerates src/rules/data/index.generated.ts from every *.json jurisdiction file.
 * Metro can't glob-import, so this keeps the import list in sync automatically.
 *
 *   npm run rules:gen
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const DATA_DIR = join(__dirname, '..', 'src', 'rules', 'data');
export const INDEX_PATH = join(DATA_DIR, 'index.generated.ts');

export const jurisdictionFileNames = (): string[] =>
  readdirSync(DATA_DIR)
    .filter((f) => f.endsWith('.json') && f !== 'groups.json')
    .sort();

const toIdentifier = (file: string) => file.replace(/\.json$/, '').replace(/[^a-zA-Z0-9]/g, '_');

export const renderIndex = (files: readonly string[]): string =>
  [
    '// AUTO-GENERATED by `npm run rules:gen` — do not edit by hand.',
    ...files.map((f) => `import ${toIdentifier(f)} from './${f}';`),
    '',
    `export const jurisdictionFiles: readonly unknown[] = [${files.map(toIdentifier).join(', ')}];`,
    '',
  ].join('\n');

if (require.main === module) {
  const files = jurisdictionFileNames();
  writeFileSync(INDEX_PATH, renderIndex(files));
  console.log(`✔ Wrote index for ${files.length} jurisdiction(s): ${files.join(', ')}`);
}
